spring:
  datasource:
    url: "jdbc:mysql://localhost/findjob"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    username: "root"
    password: "1234"

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
